name: Manually triggered min workflow - test
on:
  push:
    branches:
      - svg

jobs:
  generate-viz:
      runs-on: ubuntu-latest
      steps:
        - name: Login to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.SERVICE_PRINCIPAL_CREDS }} 
            enable-AzPSSession: true
        - uses: JosiahSiegel/AzViz-action@751d2779179e2c83cae6b4e62835ab8f1352e664
          with:
            resource-group: interview-admin-rg
            out-file: output/viz.svg
            sub-name: Pay-As-You-Go
            format: svg
        - uses: actions/upload-artifact@v2
          with:
            name: viz
            path: output/*
